#### xarray dim reduction

In [16]:
import xarray as xr
import numpy as np
import pandas as pd


def ressample(arr, N):
    A = []
    for v in np.vsplit(arr, arr.shape[0] // N):
        A.extend([*np.hsplit(v, arr.shape[0] // N)])
    return np.array(A)


In [57]:
ds = xr.DataArray(np.random.randint(1, 10, size=(5, 9)))
print(ds)
print(ds.shape)
mid_x = (ds.shape[1] // 2)
mid_y = (ds.shape[0] // 2)
print(mid_x)
print(mid_y)
c_1 = ds[:mid_y, :mid_x]
c_2 = ds[:mid_y, mid_x:]
c_3 = ds[mid_y:, :mid_x]
c_4 = ds[mid_y:, mid_x:]
print(c_1)
print(c_2)
print(c_3)
print(c_4)


#small_ds = ds[::2, ::2]


# print(small_ds)

#chunk_ds = ressample(ds, 3)
# print(chunk_ds)
# print(xr.DataArray(chunk_ds))
# print(ds[1].size)


<xarray.DataArray (dim_0: 5, dim_1: 9)>
array([[8, 7, 8, 9, 2, 4, 2, 2, 6],
       [9, 4, 1, 3, 2, 9, 9, 2, 5],
       [6, 4, 2, 9, 4, 1, 2, 4, 8],
       [1, 6, 3, 3, 7, 2, 4, 7, 8],
       [4, 2, 9, 7, 9, 2, 9, 3, 5]])
Dimensions without coordinates: dim_0, dim_1
(5, 9)
4
2
<xarray.DataArray (dim_0: 2, dim_1: 4)>
array([[8, 7, 8, 9],
       [9, 4, 1, 3]])
Dimensions without coordinates: dim_0, dim_1
<xarray.DataArray (dim_0: 2, dim_1: 5)>
array([[2, 4, 2, 2, 6],
       [2, 9, 9, 2, 5]])
Dimensions without coordinates: dim_0, dim_1
<xarray.DataArray (dim_0: 3, dim_1: 4)>
array([[6, 4, 2, 9],
       [1, 6, 3, 3],
       [4, 2, 9, 7]])
Dimensions without coordinates: dim_0, dim_1
<xarray.DataArray (dim_0: 3, dim_1: 5)>
array([[4, 1, 2, 4, 8],
       [7, 2, 4, 7, 8],
       [9, 2, 9, 3, 5]])
Dimensions without coordinates: dim_0, dim_1
