#### xarray dim reduction

In [16]:
import xarray as xr
import numpy as np
import pandas as pd


def ressample(arr, N):
    A = []
    for v in np.vsplit(arr, arr.shape[0] // N):
        A.extend([*np.hsplit(v, arr.shape[0] // N)])
    return np.array(A)


In [26]:
ds = xr.DataArray(np.random.randint(1, 10, size=(9, 9)))
print(ds)

small_ds = ds[::2, ::2]
print(small_ds)

chunk_ds = ressample(ds, 3)
#print(chunk_ds)
print(xr.DataArray(chunk_ds))


<xarray.DataArray (dim_0: 9, dim_1: 9)>
array([[8, 2, 6, 8, 5, 3, 9, 7, 9],
       [6, 2, 5, 8, 7, 2, 1, 7, 5],
       [4, 2, 3, 2, 3, 9, 3, 7, 8],
       [8, 6, 2, 3, 5, 7, 1, 2, 7],
       [8, 3, 3, 9, 9, 8, 4, 8, 5],
       [4, 2, 9, 8, 7, 9, 8, 9, 4],
       [8, 2, 9, 1, 5, 5, 7, 2, 3],
       [8, 9, 8, 2, 4, 4, 7, 4, 2],
       [8, 1, 4, 8, 2, 2, 6, 2, 9]])
Dimensions without coordinates: dim_0, dim_1
<xarray.DataArray (dim_0: 5, dim_1: 5)>
array([[8, 6, 5, 9, 9],
       [4, 3, 3, 3, 8],
       [8, 3, 9, 4, 5],
       [8, 9, 5, 7, 3],
       [8, 4, 2, 6, 9]])
Dimensions without coordinates: dim_0, dim_1
<xarray.DataArray (dim_0: 9, dim_1: 3, dim_2: 3)>
array([[[8, 2, 6],
        [6, 2, 5],
        [4, 2, 3]],

       [[8, 5, 3],
        [8, 7, 2],
        [2, 3, 9]],

       [[9, 7, 9],
        [1, 7, 5],
        [3, 7, 8]],

       [[8, 6, 2],
        [8, 3, 3],
        [4, 2, 9]],

       [[3, 5, 7],
        [9, 9, 8],
        [8, 7, 9]],

       [[1, 2, 7],
        [4, 8, 5],
 